	{level "none"
		{stand
			{accuracy 0.7}
		}
		{squat
			{accuracy 0.8}
		}
		{crawl
			{accuracy 0.9}
		}
		{cover
			{accuracy 1.0}
		}
	}
	{level "basic"
		{stand
			{accuracy 0.8}
		}
		{squat
			{accuracy 0.9}
		}
		{crawl
			{accuracy 1.0}
		}
		{cover
			{accuracy 1.1}
		}
	}
	{level "expert"
		{stand
			{accuracy 0.9}
		}
		{squat
			{accuracy 1.0}
		}
		{crawl
			{accuracy 1.1}
		}
		{cover
			{accuracy 1.2}
		}
	}
}