			{"allies_usa"
				{title "mp/alliance/allies_usa"}
				{armies "usa"}
				{armies "usa_inf_div"}
				{armies "usa_tank_div"}
				{armies "usa_storm_div"}
				{armies "usp"}
				{icon "/interface/pages/multi/flag_usa"}
			}
			{"allies_ger"
				{title "mp/alliance/allies_ger"}
				{armies "ger"}
				{armies "ger_inf_div"}
				{armies "ger_tank_div"}
				{armies "ger_storm_div"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			{"allies_rus"
				{title "mp/alliance/allies_rus"}
				{armies "rus"}
				{armies "rus_inf_div"}
				{armies "rus_tank_div"}
				{armies "rus_storm_div"}
				{armies "rup"}
				{icon "/interface/pages/multi/flag_rus"}
			}
			{"allies_eng"
				{title "mp/alliance/allies_eng"}
				{armies "eng"}
				{armies "eng_inf_div"}
				{armies "eng_tank_div"}
				{armies "eng_storm_div"}
				{armies "enp"}
				{icon "/interface/pages/multi/flag_eng"}
			}
			{"allies_jap"
				{title "mp/alliance/allies_jap"}
				{armies "jap"}
				{armies "jap_inf_div"}
				{armies "jap_tank_div"}
				{armies "jap_storm_div"}
				{icon "/interface/pages/multi/flag_jap"}
			}
			{"allies_ita"
				{title "mp/alliance/allies_ita"}
				{armies "ita"}
				{armies "ita_inf_div"}
				{armies "ita_tank_div"}
				{armies "ita_storm_div"}
				{icon "/interface/pages/multi/flag_ita"}
			}
			{"allies_fra"
				{title "mp/alliance/allies_fra"}
				{armies "fra"}
				{armies "fra_inf_div"}
				{armies "fra_tank_div"}
				{armies "fra_storm_div"}
				{icon "/interface/pages/multi/flag_fra"}
			}
			{"allies_hun"
				{title "mp/alliance/allies_hun"}
				{armies "hun"}
				{armies "hun_inf_div"}
				{armies "hun_tank_div"}
				{armies "hun_storm_div"}
				{icon "/interface/pages/multi/flag_hun"}
			}
			{"allies_rom"
				{title "mp/alliance/allies_rom"}
				{armies "rom"}
				{armies "rom_inf_div"}
				{armies "rom_tank_div"}
				{armies "rom_storm_div"}
				{icon "/interface/pages/multi/flag_rom"}
			}
			{"allies_fin"
				{title "mp/alliance/allies_fin"}
				{armies "fin"}
				{armies "fin_inf_div"}
				{armies "fin_tank_div"}
				{armies "fin_storm_div"}
				{icon "/interface/pages/multi/flag_fin"}
			}
			{"allies_bul"
				{title "mp/alliance/allies_bul"}
				{armies "bul"}
				{armies "bul_inf_div"}
				{armies "bul_tank_div"}
				{armies "bul_storm_div"}
				{icon "/interface/pages/multi/flag_bul"}
			}
			{"allies_grc"
				{title "mp/alliance/allies_grc"}
				{armies "grc"}
				{armies "grc_inf_div"}
				{armies "grc_tank_div"}
				{armies "grc_storm_div"}
				{icon "/interface/pages/multi/flag_grc"}
			}
			{"allies_dut"
				{title "mp/alliance/allies_dut"}
				{armies "dut"}
				{armies "dut_inf_div"}
				{armies "dut_tank_div"}
				{armies "dut_storm_div"}
				{icon "/interface/pages/multi/flag_dut"}
			}
			{"allies_nkr"
				{title "mp/alliance/allies_nkr"}
				{armies "nkr"}
				{armies "nkr_inf_div"}
				{armies "nkr_tank_div"}
				{armies "nkr_storm_div"}
				{icon "/interface/pages/multi/flag_nkr"}
			}
			{"allies_chn"
				{title "mp/alliance/allies_chn"}
				{armies "chn"}
				{armies "chn_inf_div"}
				{armies "chn_tank_div"}
				{armies "chn_storm_div"}
				{icon "/interface/pages/multi/flag_chn"}
			}
			{"allies_pol"
				{title "mp/alliance/allies_pol"}
				{armies "pol"}
				{armies "pol_inf_div"}
				{armies "pol_tank_div"}
				{armies "pol_storm_div"}
				{icon "/interface/pages/multi/flag_pol"}
			}
			{"axis" 
				{title "mp/alliance/axis"}
				{armies "ger"}
				{armies "ger_inf_div"}
				{armies "ger_tank_div"}
				{armies "ger_storm_div"}
				{armies "jap"}
				{armies "jap_inf_div"}
				{armies "jap_tank_div"}
				{armies "jap_storm_div"}
				{armies "ita"}
				{armies "ita_inf_div"}
				{armies "ita_tank_div"}
				{armies "ita_storm_div"}
				{armies "rom"}
				{armies "rom_inf_div"}
				{armies "rom_tank_div"}
				{armies "rom_storm_div"}
				{armies "hun"}
				{armies "hun_inf_div"}
				{armies "hun_tank_div"}
				{armies "hun_storm_div"}
				{armies "bul"}
				{armies "bul_inf_div"}
				{armies "bul_tank_div"}
				{armies "bul_storm_div"}
				{icon "/interface/pages/multi/flag_axis"}
			}
			{"allies"
				{title "mp/alliance/allies"}
				{armies "usa"}
				{armies "usa_inf_div"}
				{armies "usa_tank_div"}
				{armies "usa_storm_div"}
				{armies "usp"}
				{armies "rus"}
				{armies "rus_inf_div"}
				{armies "rus_tank_div"}
				{armies "rus_storm_div"}
				{armies "rup"}
				{armies "eng"}
				{armies "eng_inf_div"}
				{armies "eng_tank_div"}
				{armies "eng_storm_div"}
				{armies "enp"}
				{armies "fra"}
				{armies "fra_inf_div"}
				{armies "fra_tank_div"}
				{armies "fra_storm_div"}
				{armies "grc"}
				{armies "grc_inf_div"}
				{armies "grc_tank_div"}
				{armies "grc_storm_div"}
				{armies "dut"}
				{armies "dut_inf_div"}
				{armies "dut_tank_div"}
				{armies "dut_storm_div"}
				{armies "pol"}
				{armies "pol_inf_div"}
				{armies "pol_tank_div"}
				{armies "pol_storm_div"}
				{armies "chn"}
				{armies "chn_inf_div"}
				{armies "chn_tank_div"}
				{armies "chn_storm_div"}
				{icon "/interface/pages/multi/flag_allies"}
			}			