{"mercedesl3k_bul" 
	("opel_sound")
	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass2" args 1 _front)
 		else volume "glass_doorl"
 			("break_glass2" args 3 _doorl)
 		else volume "glass_doorr"
 			("break_glass2" args 3 _doorr)
 		else volume "glass_back"
 			("break_glass2" args 3 _back)
		}
 	}
}
{"mercedesl3k_bul_tr" 
	("opel_sound")
	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass2" args 1 _front)
 		else volume "glass_doorl"
 			("break_glass2" args 3 _doorl)
 		else volume "glass_doorr"
 			("break_glass2" args 3 _doorr)
 		else volume "glass_back"
 			("break_glass2" args 3 _back)
		}
 	}
} 
{"mercedesl3k_bul_art" 
	("opel_sound")
	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass2" args 1 _front)
 		else volume "glass_doorl"
 			("break_glass2" args 3 _doorl)
 		else volume "glass_doorr"
 			("break_glass2" args 3 _doorr)
 		else volume "glass_back"
 			("break_glass2" args 3 _back)
		}
 	}
}
{"mercedesl3k_bul_eng" 
	("opel_sound")
	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass2" args 1 _front)
 		else volume "glass_doorl"
 			("break_glass2" args 3 _doorl)
 		else volume "glass_doorr"
 			("break_glass2" args 3 _doorr)
 		else volume "glass_back"
 			("break_glass2" args 3 _back)
		}
 	}
}  
{"mercedesl3k_bul_bomb" 
	("opel_sound")
	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass2" args 1 _front)
 		else volume "glass_doorl"
 			("break_glass2" args 3 _doorl)
 		else volume "glass_doorr"
 			("break_glass2" args 3 _doorr)
 		else volume "glass_back"
 			("break_glass2" args 3 _back)
		}
 	}
}
{"fiat626" 
	("opel_sound")
	{on bullet_hit
 		{if volume "glass_1"
 			("break_glass2" args 1 _1)
 		else volume "glass_2"
 			("break_glass2" args 1 _2)
 		}
 	}
}
{"fiat626_art" 
	("opel_sound")
	{on bullet_hit
 		{if volume "glass_1"
 			("break_glass2" args 1 _1)
 		else volume "glass_2"
 			("break_glass2" args 1 _2)
 		}
 	}
}
{"fiat626_bomb" 
	("opel_sound")
	{on bullet_hit
 		{if volume "glass_1"
 			("break_glass2" args 1 _1)
 		else volume "glass_2"
 			("break_glass2" args 1 _2)
 		}
 	}
}
{"fiat626_eng" 
	("opel_sound")
	{on bullet_hit
 		{if volume "glass_1"
 			("break_glass2" args 1 _1)
 		else volume "glass_2"
 			("break_glass2" args 1 _2)
 		}
 	}
}