{"np_sdkfz251_rom"
	("sdkfz250_sound")
}
{"np_sdkfz251_9rom"
	("sdkfz250_sound")
	("shell_ejection")
}
{"mercedesl3k_rom" 
	("opel_sound")
	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass2" args 1 _front)
 		else volume "glass_doorl"
 			("break_glass2" args 3 _doorl)
 		else volume "glass_doorr"
 			("break_glass2" args 3 _doorr)
 		else volume "glass_back"
 			("break_glass2" args 3 _back)
		}
 	}
}
{"mercedesl3k_rom_tr" 
	("opel_sound")
	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass2" args 1 _front)
 		else volume "glass_doorl"
 			("break_glass2" args 3 _doorl)
 		else volume "glass_doorr"
 			("break_glass2" args 3 _doorr)
 		else volume "glass_back"
 			("break_glass2" args 3 _back)
		}
 	}
} 
{"mercedesl3k_rom_art" 
	("opel_sound")
	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass2" args 1 _front)
 		else volume "glass_doorl"
 			("break_glass2" args 3 _doorl)
 		else volume "glass_doorr"
 			("break_glass2" args 3 _doorr)
 		else volume "glass_back"
 			("break_glass2" args 3 _back)
		}
 	}
}
{"mercedesl3k_rom_eng" 
	("opel_sound")
	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass2" args 1 _front)
 		else volume "glass_doorl"
 			("break_glass2" args 3 _doorl)
 		else volume "glass_doorr"
 			("break_glass2" args 3 _doorr)
 		else volume "glass_back"
 			("break_glass2" args 3 _back)
		}
 	}
}  
{"mercedesl3k_rom_bomb" 
	("opel_sound")
	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass2" args 1 _front)
 		else volume "glass_doorl"
 			("break_glass2" args 3 _doorl)
 		else volume "glass_doorr"
 			("break_glass2" args 3 _doorr)
 		else volume "glass_back"
 			("break_glass2" args 3 _back)
		}
 	}
}
