{"renault_aa"
	("opel_sound")
}
{"renault_art"
	("opel_sound")
}
{"renault_inf"
	("opel_sound")
}
{"renault_eng"
	("opel_sound")
}
{"cckw352_fr"
	("gmc_sound")
 	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass2" args 1 _front)
 		else volume "glass_doorleft"
 			("break_glass2" args 3 _doorleft)
 		else volume "glass_doorright"
 			("break_glass2" args 3 _doorright)
 		else volume "glass_back"
 			("break_glass2" args 3 _back)
		else volume "glass_lampr"
 			("break_glass2" args 3 _lampr)
 		else volume "glass_lampl"
 			("break_glass2" args 3 _lampl)
		}
 	}
}
{"cckw352_fr_ai"
	("gmc_sound")
 	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass2" args 1 _front)
 		else volume "glass_doorleft"
 			("break_glass2" args 3 _doorleft)
 		else volume "glass_doorright"
 			("break_glass2" args 3 _doorright)
 		else volume "glass_back"
 			("break_glass2" args 3 _back)
		else volume "glass_lampr"
 			("break_glass2" args 3 _lampr)
 		else volume "glass_lampl"
 			("break_glass2" args 3 _lampl)
		}
 	}
}
{"cckw352_fr_art"
	("gmc_sound")
 	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass2" args 1 _front)
 		else volume "glass_doorleft"
 			("break_glass2" args 3 _doorleft)
 		else volume "glass_doorright"
 			("break_glass2" args 3 _doorright)
 		else volume "glass_back"
 			("break_glass2" args 3 _back)
		else volume "glass_lampr"
 			("break_glass2" args 3 _lampr)
 		else volume "glass_lampl"
 			("break_glass2" args 3 _lampl)
		}
 	}
}
{"cckw352_fr_2"
	("gmc_sound")
 	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass2" args 1 _front)
 		else volume "glass_doorleft"
 			("break_glass2" args 3 _doorleft)
 		else volume "glass_doorright"
 			("break_glass2" args 3 _doorright)
 		else volume "glass_back"
 			("break_glass2" args 3 _back)
		else volume "glass_lampr"
 			("break_glass2" args 3 _lampr)
 		else volume "glass_lampl"
 			("break_glass2" args 3 _lampl)
		}
 	}
}
{"renault_eng44"
	("opel_sound")
}
{"m3a1scout_fr"
	("gmc_sound")
}				