{"panhard tank"
	{on "add_movement_sound" overload
		{link_sound "move"		"vehicle/wheels/wheels"		}
		{link_sound "engine"		"vehicle/engine/Panhard_178"	}
		{link_sound "engine_end"	"vehicle/engine/Panhard_178_end"}
		{link_sound "rotate_turret" 	"vehicle/turret/light1"		}
		{link_sound "exhaust"		"vehicle/engine/Panhard_178_up"	}
		{link_sound "idle"		"vehicle/engine/Panhard_178"	}
	}
	("burn_by_engine" args 0.2)
}
{"p16m29 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/r35"		}
		{link_sound "engine"			"vehicle/engine/r35"		}
		{link_sound "engine_end"		"vehicle/engine/r35_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/medium1"	}
		{link_sound "exhaust"			"vehicle/engine/r35_up" 	}
		{link_sound "idle"			"vehicle/engine/truck_idle"		}
	}
	("burn_by_engine" args 0.3)
}
{"laffly_s15_toe tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/wheels/wheels"		}
		{link_sound "engine"			"vehicle/engine/r35"		}
		{link_sound "engine_end"		"vehicle/engine/r35_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/light1"		}
		{link_sound "exhaust"			"vehicle/engine/r35_up" 	}
		{link_sound "idle"			"vehicle/engine/truck_idle"		}
	}
	("burn_by_engine" args 0.3)
}
{"amr35-13mm tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/l6-40"		}
		{link_sound "engine"			"vehicle/engine/t60"		}
		{link_sound "engine_end"		"vehicle/engine/t60_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/light1"		}
		{link_sound "exhaust"			"vehicle/engine/t60_up" 	}
		{link_sound "idle"			"vehicle/engine/t60"		}
	}
	("burn_by_engine" args 0.3)
}
{"amr35-25m tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/l6-40"		}
		{link_sound "engine"			"vehicle/engine/t60"		}
		{link_sound "engine_end"		"vehicle/engine/t60_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/light1"		}
		{link_sound "exhaust"			"vehicle/engine/t60_up" 	}
		{link_sound "idle"			"vehicle/engine/t60"		}
	}
	("burn_by_engine" args 0.3)
}
{"ft17 tank"
	("t26_sound")
	("burn_by_engine" args 0.3)
}
{"ft17m31 tank"
	("t26_sound")
	("burn_by_engine" args 0.3)
}
{"bs-75 tank"
	("t26_sound")
	("burn_by_engine" args 0.3)
}
{"r35 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/r35"		}
		{link_sound "engine"			"vehicle/engine/r35"		}
		{link_sound "engine_end"		"vehicle/engine/r35_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/small1"	}
		{link_sound "exhaust"			"vehicle/engine/r35_up" 	}
		{link_sound "idle"			"vehicle/engine/r35"		}
	}
	("burn_by_engine" args 0.3)
}
{"r39 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/r35"		}
		{link_sound "engine"			"vehicle/engine/r35"		}
		{link_sound "engine_end"		"vehicle/engine/r35_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/small1"	}
		{link_sound "exhaust"			"vehicle/engine/r35_up" 	}
		{link_sound "idle"			"vehicle/engine/r35"		}
	}
	("burn_by_engine" args 0.3)
}
{"h35 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/r35"		}
		{link_sound "engine"			"vehicle/engine/m3a1_stuart"	}
		{link_sound "engine_end"		"vehicle/engine/m3a1_stuart_end"}
		{link_sound "rotate_turret" 		"vehicle/turret/small1"	}
		{link_sound "exhaust"			"vehicle/engine/m3a1_stuart_up"	}
		{link_sound "idle"			"vehicle/engine/m3a1_stuart"	}
	}
	("burn_by_engine" args 0.3)
}
{"h39 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/r35"		}
		{link_sound "engine"			"vehicle/engine/m3a1_stuart"	}
		{link_sound "engine_end"		"vehicle/engine/m3a1_stuart_end"}
		{link_sound "rotate_turret" 		"vehicle/turret/small1"	}
		{link_sound "exhaust"			"vehicle/engine/m3a1_stuart_up"	}
		{link_sound "idle"			"vehicle/engine/m3a1_stuart"	}
	}
	("burn_by_engine" args 0.3)
}
{"h39tral tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/r35"		}
		{link_sound "engine"			"vehicle/engine/m3a1_stuart"	}
		{link_sound "engine_end"		"vehicle/engine/m3a1_stuart_end"}
		{link_sound "rotate_turret" 		"vehicle/turret/small1"	}
		{link_sound "exhaust"			"vehicle/engine/m3a1_stuart_up"	}
		{link_sound "idle"			"vehicle/engine/m3a1_stuart"	}
	}
}
{"s35 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/mk2"		}
		{link_sound "engine"			"vehicle/engine/somua"		}
		{link_sound "engine_end"		"vehicle/engine/somua_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/small1"	}
		{link_sound "exhaust"			"vehicle/engine/somua_up" 	}
		{link_sound "idle"			"vehicle/engine/somua"		}
	}
	("burn_by_engine" args 0.3)
}
{"chardebat_d2 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/bishop"		}
		{link_sound "engine"			"vehicle/engine/somua"		}
		{link_sound "engine_end"		"vehicle/engine/somua_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/small1"	}
		{link_sound "exhaust"			"vehicle/engine/somua_up" 	}
		{link_sound "idle"			"vehicle/engine/somua"		}
	}
	("burn_by_engine" args 0.3)
}
{"b1b_fra tank"
	("b1bis_sound")
	{on fire "gun2"
        		{view start "flashbarrel11"}
		{view start "flashbarrel11s"}
		{ani_play "fire1"}
		{delay 0.8
			{view pause "flashbarrel11"}
		}
		{delay 0.2
			{view pause "flashbarrel11s"}
		}
	}
}
{"b1b_flamm tank"
	("b1bis_sound")
   	{on spawn   
   		{add_view "flamer_fire" "flame1" "foresight11"}
  		{add_view "flamer_fire_barrel" "fire1" "foresight11"}
		{view show   "fire1"}
	 	{view start   "fire1"}
   	}
   	{on operatable on	
		{view start	"fire1"}
	}	
	{on operatable off		
		{view stop	"fire1"}
	}
	{on break_armor
		{if name "blast"
			{if volume "body"
				{call "explosion"}
			}
                		}
	}
	{on bullet_hit
		{if volume "body"
			{if  tagged "isbodypierced"
				{if rand 0.3
					{call "_explosion"}
					{tags remove "isbodypierced"}
				}
			}
		}
	}
	{on "_explosion"
		{call "__explosion"}
		{spawn "fuel_die"}
		{blastwave c4 5 r0 4 r1 15}
		{fire radius 5 time 15 heating 10}
	}
	{on "__explosion"
		{set "big_explosion" 0}
		{if explosive_amount 50         
			{blastwave c4 30 r0 8 r1 16}     
			{blastwave c4 3 r0 20 r1 30}
			{spawn "train_die" "basis"}
			{set "big_explosion" 1}
		}
	}
	{on fire "flamer1"
		{view start	"flame1"}
		{kill_delay "fire1"}
		{delay 0.5 "fire1"
			{view pause	"flame1"}
		}
	}
	("burn_by_engine" args 0.3)	
}
{"np_lorraine_fr tank"
	("lorraine_sound")
	("burn_by_engine" args 0.3)
}
{"np_lorrai_fr tank"
	("lorraine_sound")
	("burn_by_engine" args 0.3)
}
{"pzkpfw35t tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/pz35t"		}
		{link_sound "engine"			"vehicle/engine/pz35"		}
		{link_sound "engine_end"		"vehicle/engine/pz35_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/pz38t_turret"	}
		{link_sound "exhaust"			"vehicle/engine/pz35_up"	}
		{link_sound "idle"			"vehicle/engine/pz35"		}
	}
	("burn_by_engine" args 0.3)
}
{"pz2c tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/pz2"		}
		{link_sound "engine"			"vehicle/engine/pz2"		}
		{link_sound "engine_end"		"vehicle/engine/pz2_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/light1"		}
		{link_sound "exhaust"			"vehicle/engine/pz2_up" 	}
		{link_sound "idle"			"vehicle/engine/pz2_idle"		}
	}
	("burn_by_engine" args 0.3)
}
{"mkvib tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/l6-40"		}
		{link_sound "engine"			"vehicle/engine/mkvib"		}
		{link_sound "engine_end"		"vehicle/engine/mkvib_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/light1"		}
		{link_sound "exhaust"			"vehicle/engine/mkvib_up" 	}
		{link_sound "idle"			"vehicle/engine/mkvib"		}
	}
	{on fire "gun"
		{view start "flashbarrel3"}
		{ani_play "fire_mgun"}
		{view start "shell"}
		{delay 0.1 "shell"
			{view pause "shell"}
		}
		{delay 0.4
			{view pause "flashbarrel3"}
		}
	}
	("burn_by_engine" args 0.3)
}
{"mkvibaa tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/l6-40"		}
		{link_sound "engine"			"vehicle/engine/l6-40"		}
		{link_sound "engine_end"		"vehicle/engine/l6-40_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/light1"		}
		{link_sound "exhaust"			"vehicle/engine/l6-40_up" 	}
		{link_sound "idle"			"vehicle/engine/l6-40"		}
	}
	("burn_by_engine" args 0.3)
}
{"m3stuart_early tank"
	{on spawn
		{add_view	"flash_gun_big"	"flashbarrel00"	"shooter00"	}
		{add_view	"flash_gun_big"	"flashbarrel01"	"shooter01"	}
	}
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/m3a1_stuart"	}
		{link_sound "engine"			"vehicle/engine/m3a1_stuart"	}
		{link_sound "engine_end"		"vehicle/engine/m3a1_stuart_end"}
		{link_sound "rotate_turret" 		"vehicle/turret/light"		}
		{link_sound "exhaust"			"vehicle/engine/m3a1_stuart_up"	}
		{link_sound "idle"			"vehicle/engine/m3a1_stuart"	}
	}
	{on fire "mgun2" overload
		{if  name "00"
			{view start "flashbarrel00"}
			{delay 0.8
				{view pause "flashbarrel00"}
			}
		else name "01"
			{view start "flashbarrel01"}
			{delay 0.8
				{view pause "flashbarrel01"}
			}
		}
	}
	("burn_by_engine" args 0.3)
}
{"matildamk1 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/bishop"		}
		{link_sound "engine"			"vehicle/engine/bishop"		}
		{link_sound "engine_end"		"vehicle/engine/bishop_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/medium1"	}
		{link_sound "exhaust"			"vehicle/engine/bishop_up" 	}
		{link_sound "idle"			"vehicle/engine/bishop"		}
	}
	("burn_by_engine" args 0.3)
}
{"cruisermk1 tank"
	{on "add_movement_sound" overload
		{link_sound "move"		    	"vehicle/tracks/cromwell"	}
		{link_sound "engine"			"vehicle/engine/pz2"		}
		{link_sound "engine_end"		"vehicle/engine/pz2_end"	}
		{link_sound "exhaust"			"vehicle/engine/pz2_up" 	}
		{link_sound "rotate_turret" 	"vehicle/turret/medium1"		}
		{link_sound "idle"			"vehicle/engine/pz2_idle"		}
	}
}
{"h39_fr"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/r35"		}
		{link_sound "engine"			"vehicle/engine/m3a1_stuart"	}
		{link_sound "engine_end"		"vehicle/engine/m3a1_stuart_end"}
		{link_sound "rotate_turret" 		"vehicle/turret/small1"	}
		{link_sound "exhaust"			"vehicle/engine/m3a1_stuart_up"	}
		{link_sound "idle"			"vehicle/engine/m3a1_stuart"	}
	}
	("burn_by_engine" args 0.3)
}
{"m2halftrack_fr"
	("m3_sound")
	("m3_break_glass")
	("burn_by_engine" args 0.3)
}
{"m2halftrack_fr_2"
	("m3_sound")
	("m3_break_glass")
	("burn_by_engine" args 0.3)
}
{"m4halftrack_fr"
	("m3_sound")
	("m3_break_glass")
	("burn_by_engine" args 0.3)
}
{"m5halftrack_fr"
	("m3_sound")
	("m3_break_glass")
	("burn_by_engine" args 0.3)
}
{"m17_fr"
	("m3_sound")
	("m3_break_glass")
	("burn_by_engine" args 0.3)
}
{"m3a1_fr"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m3stuart"	}
		{link_sound "engine"			"vehicle/engine/m3stuart"		}
		{link_sound "engine_end"		"vehicle/engine/tankengine_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light"	}
		{link_sound "exhaust"			"vehicle/engine/tankengine_up"	}
		{link_sound "idle"			"vehicle/engine/m3stuart"		}
	}
	("burn_by_engine" args 0.3)
}
{"m5a1_fr"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m3stuart"	}
		{link_sound "engine"			"vehicle/engine/m3stuart"		}
		{link_sound "engine_end"		"vehicle/engine/tankengine_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light"	}
		{link_sound "exhaust"			"vehicle/engine/tankengine_up"	}
		{link_sound "idle"			"vehicle/engine/m3stuart"		}
	}
	("burn_by_engine" args 0.3)
}
{"m8_fr"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m3stuart"	}
		{link_sound "engine"			"vehicle/engine/m3stuart"		}
		{link_sound "engine_end"		"vehicle/engine/tankengine_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light"	}
		{link_sound "exhaust"			"vehicle/engine/tankengine_up"	}
		{link_sound "idle"			"vehicle/engine/m3stuart"		}
	}
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"m4a3_75_fr"
	("m4a2_sound")
	("burn_by_engine" args 0.3)
}
{"m4a3_76_fr"
	("m4a2_sound")
	("burn_by_engine" args 0.3)
}
{"m7_fr"
	("m7_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"m10wolverine_fr"
	("m10wolverine_sound")
	{on "gunner_hatch_open" overload
		{ani_play "close"}
	}
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"m8grayhound_fr tank"
	("m8grayhound_sound")
	("burn_by_engine" args 0.3)
}
{"m20_fr tank"
	("m8grayhound_sound")
	("burn_by_engine" args 0.3)
}
{"renault_ue tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/l6-40"		}
		{link_sound "engine"			"vehicle/engine/t60"		}
		{link_sound "engine_end"		"vehicle/engine/t60_end"	}
		{link_sound "exhaust"			"vehicle/engine/t60_up" 	}
		{link_sound "idle"			"vehicle/engine/t60"		}
	}
	("burn_by_engine" args 0.3)
}