;-----------------Normand Unit Pack
(define "kv_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/is"}
		{link_sound "rotate_turret" 	"vehicle/turret/heavy"	}
		{link_sound "engine"			"vehicle/engine/kv"			}
		{link_sound "engine_end"		"vehicle/engine/kv_end"		}
		{link_sound "exhaust"			"vehicle/engine/m4a2_up"		}
		{link_sound "idle"			"vehicle/engine/kv_idle"}
	}
)
(define "is_sound"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/is"		}
		{link_sound "rotate_turret" 		"vehicle/turret/heavy1"		}
		{link_sound "engine"			"vehicle/engine/is"		}
		{link_sound "engine_end"		"vehicle/engine/is_end"		}
		{link_sound "exhaust"			"vehicle/engine/m4a2_up"	}
		{link_sound "idle"			"vehicle/engine/is2_idle"	}
	}
)
(define "ba20_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/wheels/wheels"	}
		{link_sound "engine"			"vehicle/engine/ba20"		}
		{link_sound "engine_end"		"vehicle/engine/ba20_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light1"	}
		{link_sound "exhaust"			"vehicle/engine/ba20_up"	}
		{link_sound "idle"			"vehicle/engine/ba20"	}
	}
)
(define "ba10_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/wheels/blitz"	}
		{link_sound "engine"			"vehicle/engine/gaz_idle"   	}
		{link_sound "engine_end"		"vehicle/engine/zis_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light1"	}
		{link_sound "exhaust"			"vehicle/engine/zis_up"	}
		{link_sound "idle"			"vehicle/engine/gaz_idle"}
	}
)
(define "t26_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/bt"			}
		{link_sound "rotate_turret" 	"vehicle/turret/light"		}
		{link_sound "engine"			"vehicle/engine/t26"		}
		{link_sound "engine_end"		"vehicle/engine/t26_end"	}
		{link_sound "exhaust"			"vehicle/engine/t26_up"	}
		{link_sound "idle"			"vehicle/engine/t26"		}
	}
)
(define "t50_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/t-70"		}
		{link_sound "engine"			"vehicle/engine/bt"		}
		{link_sound "engine_end"		"vehicle/engine/bt_end"	}
		{link_sound "exhaust"			"vehicle/engine/bt_up"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light"	}
		{link_sound "idle"			"vehicle/engine/bt"		}
	}
)
(define "t26_2_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/bt"			}
		{link_sound "rotate_turret" 	"vehicle/turret/light"		}
		{link_sound "rotate_turret2" 	"vehicle/turret/light"		}
		{link_sound "engine"			"vehicle/engine/t26"		}
		{link_sound "engine_end"		"vehicle/engine/t26_end"	}
		{link_sound "exhaust"			"vehicle/engine/t26_up"	}
		{link_sound "idle"			"vehicle/engine/t26"		}
	}
)
(define "pz1_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/pz1"	}
		{link_sound "engine"			"vehicle/engine/pz1"	}
		{link_sound "engine_end"		"vehicle/engine/pz1_end"}
		{link_sound "rotate_turret" 	"vehicle/turret/light1"	}
		{link_sound "exhaust"			"vehicle/engine/pz1_up"	}
		{link_sound "idle"			"vehicle/engine/pz1_idle"		}
	}
)
(define "pz38_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/hetzer"	}
		{link_sound "engine"			"vehicle/engine/pz38"		}
		{link_sound "engine_end"		"vehicle/engine/pz38_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light1"		 }
		{link_sound "exhaust"			"vehicle/engine/pz38_up"	}
		{link_sound "idle"			"vehicle/engine/hetzer_idle"}
	}
)
(define "su76_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/t-70"}
		{link_sound "engine"			"vehicle/engine/t26"		}
		{link_sound "engine_end"		"vehicle/engine/bt_end"	}
		{link_sound "exhaust"			"vehicle/engine/bt_up"	}
		{link_sound "idle"			"vehicle/engine/t26"		}
	}
)
(define "bt7_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/bt"		}
		{link_sound "engine"			"vehicle/engine/bt"		}
		{link_sound "engine_end"		"vehicle/engine/bt_end"	}
		{link_sound "exhaust"			"vehicle/engine/bt_up"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light"	}
		{link_sound "idle"			"vehicle/engine/bt"		}
	}
)
(define "bt5_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/bt"		}
		{link_sound "engine"			"vehicle/engine/bt"		}
		{link_sound "engine_end"		"vehicle/engine/bt_end"	}
		{link_sound "exhaust"			"vehicle/engine/bt_up"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light"	}
		{link_sound "idle"			"vehicle/engine/bt"		}
	}
)
(define "m2a4_sound"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/m3a1_stuart"	}
		{link_sound "engine"			"vehicle/engine/m3a1_stuart"	}
		{link_sound "engine_end"		"vehicle/engine/m3a1_stuart_end"}
		{link_sound "rotate_turret" 		"vehicle/turret/light"		}
		{link_sound "exhaust"			"vehicle/engine/m3a1_stuart_up"	}
		{link_sound "idle"			"vehicle/engine/m3a1_stuart"	}
	}
)
(define "lorraine_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/pz3"}
		{link_sound "engine"			"vehicle/engine/lorraine"		}
		{link_sound "engine_end"		"vehicle/engine/lorraine_end"	}
		{link_sound "exhaust"			"vehicle/engine/lorraine_up"	}
		{link_sound "idle"			"vehicle/engine/lorraine"	}
	}
)
(define "m4a2_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m4a2"  }
		{link_sound "engine"			"vehicle/engine/m4a2"		}
		{link_sound "engine_end"		"vehicle/engine/m4a2_end"	}
		{link_sound "exhaust"			"vehicle/engine/m4a2_up"	}
		{link_sound "rotate_turret" 	"vehicle/turret/heavy"	}
		{link_sound "idle"			"vehicle/engine/m4a2_idle"	}
	}
)
(define "b1bis_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/b1bis"}
		{link_sound "engine"			"vehicle/engine/b1bis"		}
		{link_sound "engine_end"		"vehicle/engine/b1bis_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/heavy1"	}
		{link_sound "exhaust"			"vehicle/engine/b1bis_up"	}
		{link_sound "idle"			"vehicle/engine/b1bis"		}
	}
)
(define "stz_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/chi-ha"	}
		{link_sound "engine"			"vehicle/engine/t26"		}
		{link_sound "engine_end"		"vehicle/engine/bt_end"	}
		{link_sound "exhaust"			"vehicle/engine/bt_up"	}
		{link_sound "idle"			"vehicle/engine/t26"		}
	}
)
(define "mkiv_sound"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/chi-ha"	}
		{link_sound "engine"		"vehicle/engine/mk_move"}
		{link_sound "engine_end"		"vehicle/engine/mk7_end" 	}
		{link_sound "exhaust"		"vehicle/engine/mk7_up" 	}
		{link_sound "idle"			"vehicle/engine/mk_move"}
	}
)
(define "break_glass"
 	{volumes "glass%1" disable bullet contact blast}
 	{spawn "glass_hit2" "glass%1" x}
 	{delay 0.1
 	{bone cut "glass%1"}
	}
)
(define "m3_break_glass"
	{on bullet_hit
 		{if volume "glass_front1"
 			("break_glass" args 3 _front1)
 		else volume "glass_front2"
 			("break_glass" args 3 _front2)
 		}
 	}
)
{"np_pz5a tank"
	("pz5g_sound")
	("burn_by_engine" args 0.3)
}
{"np_t50 tank"
	{on spawn
		{add_view	"flash_gun_big"	"flashbarrel00"	"shooter00"	}
		{add_view	"flash_gun_big"	"flashbarrel01"	"shooter01"	}
	}
	("t50_sound")
	("burn_by_engine" args 0.2)
	{on fire "mgun" overload
		{if  name "00"
			{view start "flashbarrel00"}
			{delay 0.8
				{view pause "flashbarrel00"}
			}
		else name "01"
			{view start "flashbarrel01"}
			{delay 0.8
				{view pause "flashbarrel01"}
			}
		}
	}
}
{"kv1s tank"
	("kv_sound")
	("burn_by_engine" args 0.2)
}
{"kv1_41 tank"
	("kv_sound")
	("burn_by_engine" args 0.2)
}
{"kv1_40 tank"
	("kv_sound")
	("burn_by_engine" args 0.2)
}
{"su152 tank"
	("kv_sound")
	("burn_by_engine" args 0.2)
}

{"np_m5 tank"
	("m3_sound")
	("m3_break_glass")
	("burn_by_engine" args 0.3)
}
{"np_m17 tank"
	("m3_sound")
	("m3_break_glass")
	("burn_by_engine" args 0.3)
}
{"np_m17_en tank"
	("m3_sound")
	("m3_break_glass")
	("burn_by_engine" args 0.3)
}
{"np_m15a1 tank"
	{on spawn
		{add_view	"flash_gun_big"	"flashbarrel00"	"shooter00"	}
		{add_view	"flash_gun_big"	"flashbarrel01"	"shooter01"	}
	}
	("m3_sound")
	("m3_break_glass")
	("burn_by_engine" args 0.3)
	{on fire "mgun"
		{if  name "00"
			{view start "flashbarrel00"}
			{delay 0.8
				{view pause "flashbarrel00"}
			}
		else name "01"
			{view start "flashbarrel01"}
			{delay 0.8
				{view pause "flashbarrel01"}
			}
		}
	}
}
{"np_t48 tank"
	("m3_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"np_t48_us tank"
	("m3_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"np_t48_en tank"
	("m3_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"np_t19 tank"
	("m3_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"np_t15 tank"
	("m3_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"np_sdkfz234 tank"
	("sdkfz234_sound")
	("burn_by_engine" args 0.3)
}	
{"np_sdkfz234_1 tank"
	("sdkfz234_sound")
	("burn_by_engine" args 0.3)
}
{"np_sdkfz234_3 tank"
	("sdkfz234_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"np_sdkfz234_4 tank"
	("sdkfz234_sound")
	{on fire "gun"
        		{ani_play "fire"}
		{ani_play "start"}
		{call "spawn_shell_tank"}
	}
	{on "spawn_shell_tank"
		{start_sound "weapon/shot/shell"}
		{add_view "smoke_zenit" "smoke_shell" "fx_invers"}
		{view start "smoke_shell"}
		{delay 2.5 0.5
			{view stop "smoke_shell"}
		}
		{spawn "shell_cannon" "fx_invers" x scale 0.014
			{impulse up 1.5 0.5 dir -4.5 0.7 cz 0.2 0.1 com}
			{add_view "smoke_zenit" "smoke_shell" "fx_shellsmoke"}
			{view start "smoke_shell"}
			{delay_effect 3 1 "stop"}
			{delay 3 0.5
				{hide 15}
			}
		}
	}
	("burn_by_engine" args 0.3)
}
{"np_su14 tank"		
	("mk7_sound")
	("burn_by_engine" args 0.3)
}
{"t34_41 tank"
	("t34_sound")
	("burn_by_engine" args 0.2)
}
{"t34_42 tank"
	("t34_sound")
	("burn_by_engine" args 0.2)
}
{"np_ba20 tank"
	("ba20_sound")
	("burn_by_engine" args 0.2)
}
{"np_ho_ki tank"
	("hanomag_sound")
	("burn_by_engine" args 0.3)
}
{"np_marder135 tank"
	("lorraine_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"np_sdkfz135_1 tank"
	("lorraine_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"np_lorraine tank"
	("lorraine_sound")
	("burn_by_engine" args 0.3)
}
{"np_lorrai_37 tank"
	("lorraine_sound")
	("burn_by_engine" args 0.3)
}
{"np_lorrai_37_47 tank"
	("lorraine_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"m4a1 tank"
	("m4a2_sound")
	("burn_by_engine" args 0.3)
}
{"m4a1_76w tank"
	("m4a2_sound")
	("burn_by_engine" args 0.3)
}
{"m4a1_eng tank"
	("m4a2_sound")
	("burn_by_engine" args 0.3)
}
{"m4a1_76w_eng tank"
	("m4a2_sound")
	("burn_by_engine" args 0.3)
}
{"m4a2 tank"
	("m4a2_sound")
	("burn_by_engine" args 0.3)
}
{"m4a2_76w tank"
	("m4a2_sound")
	{on fire "gun"
				{ani_play "fire"}
        		{ani_play "fire2_76"}
	}
	("burn_by_engine" args 0.3)
}
{"b1bis tank"
	("b1bis_sound")
	{on fire "gun2"
        		{view start "flashbarrel11"}
		{view start "flashbarrel11s"}
		{ani_play "fire1"}
		{delay 0.8
			{view pause "flashbarrel11"}
		}
		{delay 0.2
			{view pause "flashbarrel11s"}
		}
	}
}
{"t35 tank"		
	{on spawn
		{add_view	"flash_gun_big_vehicle"	"flashbarrel8"	"Foresight8"}
		{add_view	"flash_gun_big_vehicle"	"flashbarrel9"	"Foresight9"}
		{add_view	"flash_gun_big_vehicle"	"flashbarrel10"	"Foresight10"}
		{add_view	"flash_cannon_small"	"flashbarrel13"	"Foresight11"}
		{add_view	"powdersmoke_big"		"flashbarrel13s"	"Foresight11"}
	}
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/mk7"	}
		{link_sound "engine"			"vehicle/engine/mk7"		}
		{link_sound "engine_end"		"vehicle/engine/mk7_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/mk7_turret"		}
		{link_sound "rotate_turret2" 	"vehicle/turret/light"		}
		{link_sound "rotate_turret3" 	"vehicle/turret/light"		}
		{link_sound "rotate_turret4" 	"vehicle/turret/light1"		}
		{link_sound "rotate_turret5" 	"vehicle/turret/light1"		}
		{link_sound "exhaust"			"vehicle/engine/mk7_up" 	}
		{link_sound "idle"			"vehicle/engine/mk7"		}
	}
	("burn_by_engine" args 0.3)
	{on fire "mgun4"
		{view start "flashbarrel8"}
		{delay 0.5
			{view pause "flashbarrel8"}
		}
	}
	{on fire "mgun5"
		{view start "flashbarrel9"}
		{delay 0.5
			{view pause "flashbarrel9"}
		}
	}
	{on fire "mgun6"
		{view start "flashbarrel10"}
		{delay 0.5
			{view pause "flashbarrel10"}
		}
	}
	{on fire "gun2"
        		{view start "flashbarrel13"}
		{view start "flashbarrel13s"}
		{ani_play "fire2"}
		{delay 0.8
			{view pause "flashbarrel13"}
		}
		{delay 0.2
			{view pause "flashbarrel13s"}
		}
	}
	{on fire "gun3"
        		{view start "flashbarrel12"}
		{view start "flashbarrel12s"}
		{ani_play "fire3"}
		{delay 0.8
			{view pause "flashbarrel12"}
		}
		{delay 0.2
			{view pause "flashbarrel12s"}
		}
	}
}
{"m3grant tank"
	{on spawn
		{add_view	"flash_gun_big"	"flashbarrel00"	"shooter00"	}
		{add_view	"flash_gun_big"	"flashbarrel01"	"shooter01"	}
	}
	("m4_sound")
	("burn_by_engine" args 0.3)
	{on fire "gun2"
        		{view start "flashbarrel11"}
		{view start "flashbarrel11s"}
		{ani_play "fire2"}
		{delay 0.8
			{view pause "flashbarrel11"}
		}
		{delay 0.2
			{view pause "flashbarrel11s"}
		}
	}
	{on fire "mgun" overload
		{if  name "00"
			{view start "flashbarrel00"}
			{delay 0.5
				{view pause "flashbarrel00"}
			}
		else name "01"
			{view start "flashbarrel01"}
			{delay 0.5
				{view pause "flashbarrel01"}
			}
		}
	}
}
{"dickermax tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}
{"pz4f_1 tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}
{"pz4f_2 tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}
{"sdkfz221 tank"
	("sdkfz_sound")
	("burn_by_engine" args 0.3)
}
{"np_sdkfz4 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/sdkfz10"	 }
		{link_sound "engine"			"vehicle/engine/sdkfz250"	 }
		{link_sound "engine_end"		"vehicle/engine/sdkfz250_end"}
		{link_sound "rotate_turret" 	"vehicle/turret/light1"		 }
		{link_sound "exhaust"			"vehicle/engine/sdkfz250_up" }
		{link_sound "idle"			"vehicle/engine/sdkfz_idle"	 }
	}
	{on "gunner_hatch_open" overload
		{ani_play "open2"}
	}
	("burn_by_engine" args 0.3)
}
{"pz6h tank"
	("pz6_sound")
	{on "gunner_hatch_open" overload
		{ani_play "open2"}
	}
	("burn_by_engine" args 0.3)
}
{"sdkfz182h tank"
	("pz6_sound")
	("burn_by_engine" args 0.3)
}
{"sdkfz182b tank"
	("pz6_sound")
	("burn_by_engine" args 0.3)
	{on fire "gun"
        		{ani_play "fire_p"}
	}	
}
{"stug3c tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}
{"stug3f tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}
{"pzkpfw38t_b tank"
	("pz38_sound")
	("burn_by_engine" args 0.3)
}
{"pzkpfw38t_hun tank"
	("pz38_sound")
	("burn_by_engine" args 0.3)
}
{"ba10 tank"
	("sdkfz234_sound")
	("burn_by_engine" args 0.3)
}
{"m4hst tank"
	("m3_sound")
	("burn_by_engine" args 0.3)
}
{"karlthor tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/karl_track"		}
		{link_sound "engine"			"vehicle/engine/karl"		}
		{link_sound "engine_end"		"vehicle/engine/karl_end"	}
		{link_sound "exhaust"			"vehicle/engine/karl_up" 	}
		{link_sound "idle"			"vehicle/engine/karl"		}
	}
	("burn_by_engine" args 0.3)
}
{"np_sdkfz231 tank"
	("sdkfz234_sound")
	("burn_by_engine" args 0.3)
}
{"pz4e tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}
{"pz4c tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}	
{"pz4f tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}
{"pz3_m tank"
	("pz3_sound")
	("burn_by_engine" args 0.3)
	{on fire "gun"
        		{ani_play "fire2"}
	}	
}
{"pz3j tank"
	("pz3_sound")
	("burn_by_engine" args 0.3)	
}
{"su85m tank"
	("t34_sound")
	("burn_by_engine" args 0.2)
	{on fire "gun"
        		{ani_play "fire2"}
	}
}
{"t34m2 tank"
	("t34_sound")
	("burn_by_engine" args 0.2)
	{on "stop_on"
		{ani_stop "start2"}
		{ani_play "stop2"}
		{view show "stop_signal"}
		{view start "stop_signal"}
		{delay 1
			{view hide "stop_signal"}
		}
	}
	{on move on
		{stop_sound "move_end"}
		{play_sound "move" 1}
		{call "exhaust_on"}
		{ani_stop "stop2"}
		{ani_play "start2"}
	}
	{on fire "gun"
        		{ani_play "fire2"}
	}
}
{"ot34_2 tank"
	("t34_sound")
	("burn_by_engine" args 0.2)
	{on spawn   
		{add_view "flamer_fire" "flame1" "foresight4"}
		{add_view "flamer_fire_barrel" "fire1" "foresight4"}
		{view show   "fire1"}
		{view start   "fire1"}
	}
	{on break_armor
		{if name "blast"
			{if volume "body"
				{call "explosion"}
			}
                		}
	}
	{on bullet_hit
		{if volume "body"
			{if  tagged "isbodypierced"
				{if rand 0.3
					{call "_explosion"}
					{tags remove "isbodypierced"}
				}
			}
		}
	}
	{on "_explosion"
		{call "__explosion"}
		{spawn "fuel_die"}
		{blastwave c4 5 r0 4 r1 15}
		{fire radius 5 time 15 heating 10}
	}
	{on "__explosion"
		{set "big_explosion" 0}
		{if explosive_amount 50         
			{blastwave c4 30 r0 8 r1 16}     
			{blastwave c4 3 r0 20 r1 30}
			{spawn "train_die" "basis"}
			{set "big_explosion" 1}
		}
	}
	{on fire "mgun1"
		{view start   "flame1"}
		{kill_delay "fire1"}
		{delay 0.5 "fire1"
			{view pause   "flame1"}
		}
	}
	{on operatable on	
		{view start	"fire1"}
	}	
	{on operatable off		
		{view stop	"fire1"}
	}
}
{"pz3_m_flamer tank"
	("pz3_sound")
	("burn_by_engine" args 0.3)	
	{on spawn
		{add_view "flamer_fire" "flame1" "foresight1"}
		{add_view "flamer_fire_barrel" "fire1" "foresight1"}
		{view show	"fire1"}
		{view start	"fire1"}
	}
	{on operatable on	
		{view start	"fire1"}
	}	
	{on operatable off		
		{view stop	"fire1"}
	}
	{on break_armor
		{if name "blast"
			{if volume "body"
				{call "explosion"}
			}
                		}
	}
	{on bullet_hit
		{if volume "body"
			{if  tagged "isbodypierced"
				{if rand 0.3
					{call "_explosion"}
					{tags remove "isbodypierced"}
				}
			}
		}
	}
	{on "_explosion"
		{call "__explosion"}
		{spawn "fuel_die"}
		{blastwave c4 5 r0 4 r1 15}
		{fire radius 5 time 15 heating 10}
	}
	{on "__explosion"
		{set "big_explosion" 0}
		{if explosive_amount 50         
			{blastwave c4 30 r0 8 r1 16}     
			{blastwave c4 3 r0 20 r1 30}
			{spawn "train_die" "basis"}
			{set "big_explosion" 1}
		}
	}
	{on fire "flamer1"
		{view start	"flame1"}
		{kill_delay "fire1"}
		{delay 0.5 "fire1"
			{view pause	"flame1"}
		}
	}
}
{"t-26_1931 tank"
	("t26_2_sound")
	("burn_by_engine" args 0.2)
}
{"t-26_1931a tank"
	("t26_2_sound")
	("burn_by_engine" args 0.2)
}
{"t-26_1933 tank"
	("t26_sound")
	("burn_by_engine" args 0.2)
}
{"ot-130 tank"
	("t26_sound")
	("burn_by_engine" args 0.3)	
	{on spawn
		{add_view "flamer_fire" "flame1" "foresight1"}
		{add_view "flamer_fire_barrel" "fire1" "foresight1"}
		{view show	"fire1"}
		{view start	"fire1"}
	}
	{on operatable on	
		{view start	"fire1"}
	}	
	{on operatable off		
		{view stop	"fire1"}
	}
	{on break_armor
		{if name "blast"
			{if volume "body"
				{call "explosion"}
			}
                		}
	}
	{on bullet_hit
		{if volume "body"
			{if  tagged "isbodypierced"
				{if rand 0.3
					{call "_explosion"}
					{tags remove "isbodypierced"}
				}
			}
		}
	}
	{on "_explosion"
		{call "__explosion"}
		{spawn "fuel_die"}
		{blastwave c4 5 r0 4 r1 15}
		{fire radius 5 time 15 heating 10}
	}
	{on "__explosion"
		{set "big_explosion" 0}
		{if explosive_amount 50         
			{blastwave c4 30 r0 8 r1 16}     
			{blastwave c4 3 r0 20 r1 30}
			{spawn "train_die" "basis"}
			{set "big_explosion" 1}
		}
	}
	{on fire "flamer1"
		{view start	"flame1"}
		{kill_delay "fire1"}
		{delay 0.5 "fire1"
			{view pause	"flame1"}
		}
	}
}
{"challenger_a30 tank"
	{on "add_movement_sound" overload
		{link_sound "move"		    	"vehicle/tracks/cromwell"	}
		{link_sound "engine"			"vehicle/engine/cromwell"		}
		{link_sound "engine_end"		"vehicle/engine/cromwell_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/churchill_turret"	}
		{link_sound "exhaust"			"vehicle/engine/cromwell_up"	}
		{link_sound "idle"			"vehicle/engine/cromwell"		}
	}
	("burn_by_engine" args 0.3)
}
{"np_is1 tank"
	("kv_sound")
	("burn_by_engine" args 0.2)
}
{"pz5a tank"
	("pz5g_sound")
	("burn_by_engine" args 0.3)
}
{"kv8_41 tank"
	("kv_sound")
	("burn_by_engine" args 0.2)
	{on spawn   
		{add_view "flamer_fire" "flame1" "foresight5"}
		{add_view "flamer_fire_barrel" "fire1" "foresight5"}
		{view show   "fire1"}
		{view start   "fire1"}
	}
	{on break_armor
		{if name "blast"
			{if volume "body"
				{call "explosion"}
			}
                		}
	}
	{on bullet_hit
		{if volume "body"
			{if  tagged "isbodypierced"
				{if rand 0.3
					{call "_explosion"}
					{tags remove "isbodypierced"}
				}
			}
		}
	}
	{on "_explosion"
		{call "__explosion"}
		{spawn "fuel_die"}
		{blastwave c4 5 r0 4 r1 15}
		{fire radius 5 time 15 heating 10}
	}
	{on "__explosion"
		{set "big_explosion" 0}
		{if explosive_amount 50         
			{blastwave c4 30 r0 8 r1 16}     
			{blastwave c4 3 r0 20 r1 30}
			{spawn "train_die" "basis"}
			{set "big_explosion" 1}
		}
	}
	{on fire "mgun2"
		{view start   "flame1"}
		{kill_delay "fire1"}
		{delay 0.5 "fire1"
			{view pause   "flame1"}
		}
	}
	{on operatable on	
		{view start	"fire1"}
	}	
	{on operatable off		
		{view stop	"fire1"}
	}
}
{"pz4d tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}
{"pz3e tank"
	{on spawn
		{add_view	"flash_gun_big"	"flashbarrel00"	"shooter00"	}
		{add_view	"flash_gun_big"	"flashbarrel01"	"shooter01"	}
	}
	{on fire "mgun2" overload
		{if  name "00"
			{view start "flashbarrel00"}
			{delay 0.8
				{view pause "flashbarrel00"}
			}
		else name "01"
			{view start "flashbarrel01"}
			{delay 0.8
				{view pause "flashbarrel01"}
			}
		}
	}
	("pz3_sound")
	("burn_by_engine" args 0.3)
}
{"sturmpz1 tank"
	("pz1_sound")
	("shell_ejection_tank")
}
{"bt7_37_1 tank"
	("bt7_sound")
	("burn_by_engine" args 0.3)
}
{"bt7_37_0 tank"
	("bt7_sound")
	("burn_by_engine" args 0.3)
}
{"m2halftrack tank"
	("m3_sound")
	("burn_by_engine" args 0.3)
}
{"m2halftrack_2 tank"
	("m3_sound")
	("burn_by_engine" args 0.3)
}
{"m4sherman tank"
	("m4a2_sound")
	("burn_by_engine" args 0.3)
}
{"m36b1 tank"
	("m4a2_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"m2a4 tank"
	("m2a4_sound")
	{on "init_gun"
		{add_view	"flash_gun_big_vehicle"	"flashbarrel7"	"Foresight7"}
	}
	{on fire "mgun4"
		{view start "flashbarrel7"}
		{delay 0.5
			{view pause "flashbarrel7"}
		}
	}
	("burn_by_engine" args 0.3)
}
{"t-38 tank"
	("t26_sound")
	("burn_by_engine" args 0.2)
}
{"type89 tank"
	{on "add_movement_sound" overload
		{link_sound "rotate_turret" 	"vehicle/turret/light"	}
		{link_sound "move"				"vehicle/tracks/pz1"	}
		{link_sound "engine"			"vehicle/engine/chi-ha"	}
		{link_sound "engine_end"		"vehicle/engine/mb_end"}
		{link_sound "exhaust"			"vehicle/engine/mb_up"	}
		{link_sound "idle"			"vehicle/engine/chi-ha"	}
	}
	("burn_by_engine" args 0.3)
}
{"te-ke tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/bt"		}
		{link_sound "rotate_turret" 		"vehicle/turret/light"		}
		{link_sound "engine"			"vehicle/engine/cv33"		}
		{link_sound "engine_end"		"vehicle/engine/cv33_end"	}
		{link_sound "exhaust"			"vehicle/engine/cv33_up"	}
		{link_sound "idle"			"vehicle/engine/cv33"		}
	}
	("burn_by_engine" args 0.3)
}
{"t28_l10 tank"		
	{on "init_gun"
		{add_view	"flash_gun_big_vehicle"	"flashbarrel7"	"Foresight7"}
		{add_view	"flash_gun_big_vehicle"	"flashbarrel8"	"Foresight8"}
	}
	("mk7_sound")
	("burn_by_engine" args 0.3)
	{on fire "mgun4"
		{view show  "flashbarrel7"}
		{view start "flashbarrel7"}
		{delay 0.1 "fire"
			{view hide	"flashbarrel7"}
			{view pause	"flashbarrel7"}
			{view pause	"shell"}
		}
	}
	{on fire "mgun5"
		{view show  "flashbarrel8"}
		{view start "flashbarrel8"}
		{delay 0.1 "fire"
			{view hide	"flashbarrel8"}
			{view pause	"flashbarrel8"}
			{view pause	"shell"}
		}
	}
}
{"panzerjager tank"
	("pz1_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.2)
}
{"pz4j tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}
{"t34_42m tank"
	("t34_sound")
	("burn_by_engine" args 0.2)
}
{"pz5d tank"
	("pz5g_sound")
	("burn_by_engine" args 0.3)
	{on "init_gun"
		{ani_play "fire_mg"}
	}
}
{"pz1a tank"
	{on spawn
		{add_view	"flash_gun_big_vehicle"	"flashbarrel00"	"shooter00"	}
		{add_view	"flash_gun_big_vehicle"	"flashbarrel01"	"shooter01"	}
	}
	{on fire "mgun" overload
		{if  name "00"
			{view start "flashbarrel00"}
			{delay 0.5
				{view pause "flashbarrel00"}
			}
		else name "01"
			{view start "flashbarrel01"}
			{delay 0.5
				{view pause "flashbarrel01"}
			}
		}
	}
	("pz1_sound")
	("burn_by_engine" args 0.3)
}
{"np_sdkfz8_flak tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/sdkfz250"	}
		{link_sound "engine"			"vehicle/engine/sdkfz250"		}
		{link_sound "engine_end"		"vehicle/engine/sdkfz250_end"	}
		{link_sound "exhaust"			"vehicle/engine/sdkfz250_up"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light1"	}
		{link_sound "idle"			"vehicle/engine/sdkfz250"		}
	}
	{on fire "gun"
		{ani_play "fire"}
		{ani_play "start"}
		{call "spawn_shell_tank"}
	}
	{on "spawn_shell_tank"
		{start_sound "weapon/shot/shell"}
		{add_view "smoke_zenit" "smoke_shell" "fx_invers"}
		{view start "smoke_shell"}
		{delay 2.5 0.5
			{view stop "smoke_shell"}
		}
		{spawn "shell_cannon" "fx_invers2" x scale 0.014
			{impulse up 1.5 0.5 dir -4.5 0.7 cz 0.2 0.1 com}
			{add_view "smoke_zenit" "smoke_shell" "fx_shellsmoke"}
			{view start "smoke_shell"}
			{delay_effect 3 1 "stop"}
			{delay 3 0.5
				{hide 15}
			}
		}
	}
	{on "update_lights"
		{if not sunlight
			{if operatable
				{ani_play "lights_on"}
				{call "lights_on"}
			else
				{call "lights_off"}
				{ani_play "lights_off"}
			}
		}
	}
}
{"brummbar tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
	{on fire "gun"
		{delay 1
			{ani_play "recoil"}
			{call "spawn_shell_tank"}
		}
	}
	{on "spawn_shell_tank"
		{start_sound "weapon/shot/shell"}
		{add_view "smoke_zenit" "smoke_shell" "fx_invers"}
		{view start "smoke_shell"}
		{delay 2.5 0.5
			{view stop "smoke_shell"}
		}
		{spawn "shell_cannon" "fx_invers" x scale 0.014
			{impulse up 1.5 0.5 dir -4.5 0.7 cz 0.2 0.1 com}
			{add_view "smoke_zenit" "smoke_shell" "fx_shellsmoke"}
			{view start "smoke_shell"}
			{delay_effect 3 1 "stop"}
			{delay 3 0.5
				{hide 15}
			}
		}
	}
}
{"ferdinand tank"
	("pz6_sound")
	("burn_by_engine" args 0.3)
}
{"ms-1_1 tank"
	("burn_by_engine" args 0.2)
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/ms1"		}
		{link_sound "engine"			"vehicle/engine/chi-ha"		}
		{link_sound "engine_end"		"vehicle/engine/ba11_end"	}
		{link_sound "exhaust"			"vehicle/engine/ba11_up"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light"		}
		{link_sound "idle"			"vehicle/engine/chi-ha"		}
	}
}
{"t40 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/pz35t"		}
		{link_sound "engine"			"vehicle/engine/t60"		}
		{link_sound "engine_end"		"vehicle/engine/t60_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/pz38t_turret"	}
		{link_sound "exhaust"			"vehicle/engine/t60_up"	}
		{link_sound "idle"			"vehicle/engine/t60"		}
	}
	("burn_by_engine" args 0.2)
	{on "update_bulbs"
		{if "in_water"
			{if not "eng_water" 
				{set "eng_water" 1}
				{ani_play "engine"}	
			}
			{if not velocity 0.001
				{view start "on_stead"}
				{view pause "on_move"}
				{ani_stop "propeller"}
				{ani_play "drift" loop}
					
			else
				{view start "on_move"}
				{view pause "on_stead"}
				{ani_stop "drift"}
				{ani_play "propeller" loop}
			}
		else
			{if "eng_water" 
				{set "eng_water" 0}
				{ani_play "engine_stop"}
			}
			{ani_stop "propeller"}
			{ani_stop "drift"}
			{view pause "on_stead"}
			{view pause "on_move"}
		}
	}
}
{"type87 tank"
	("sdkfz234_sound")
	("burn_by_engine" args 0.3)
}
{"humber"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/wheels/wheels"			}
		{link_sound "engine"			"vehicle/engine/sdkfz234"		}
		{link_sound "engine_end"		"vehicle/engine/sdkfz234_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light1"			}
		{link_sound "exhaust"			"vehicle/engine/sdkfz234_up"	}
		{link_sound "idle"			"vehicle/engine/sdkfz222"		}
	}
	("burn_by_engine" args 0.3)
}
{"zis_30 tank"
	("su76_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"su76 tank"
	("su76_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"na-to tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/chi-ha"	}
		{link_sound "engine"			"vehicle/engine/sdkfz251"	}
		{link_sound "engine_end"		"vehicle/engine/sdkfz251_end"	}
		{link_sound "exhaust"			"vehicle/engine/sdkfz251_up"	}
		{link_sound "idle"			"vehicle/engine/sdkfz251"	}
	}
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"ta-se tank"
	{on "add_movement_sound" overload
		{link_sound "rotate_turret" 	"vehicle/turret/light"	}
		{link_sound "move"				"vehicle/tracks/chi-ha"	}
		{link_sound "engine"			"vehicle/engine/chi-ha"	}
		{link_sound "engine_end"		"vehicle/engine/hetzer_end"}
		{link_sound "exhaust"			"vehicle/engine/hetzer_up"	}
		{link_sound "idle"			"vehicle/engine/chi-ha"	}
	}
	("burn_by_engine" args 0.3)
}
{"pz4g_43 tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}
{"m4halftrack tank"
	("burn_by_engine" args 0.3)
	("m3_sound")
	{on spawn
		{link_sound "rotate_turret" "vehicle/turret/mortar"}
		{link_sound "rotate_gun" "vehicle/turret/medium"}
		{add_view	"flash_cannon_small"		"flashbarrel1"	"Foresight1"}
		{add_view	"powdersmoke_big"		"flashbarrel1s"		"Foresight1"}
		{add_view	"smoke_zenite"		    "smkafire"		"Foresight1"}
	}
	{on fire "gun"
        		{view start "flashbarrel1"}
		{view start "flashbarrel1s"}
        		{view start "smkafire"}
		{delay 0.8
			{view pause "flashbarrel1"}
		}
		{delay 0.2
			{view pause "flashbarrel1s"}
		}
        		{delay 2.5
            			{view stop "smkafire"}
        		}
	}
}
{"gun_carrier_3_inch tank"
	("mk7_sound")
	("burn_by_engine" args 0.3)
	{on spawn
		{link_sound "rotate_turret" "vehicle/turret/mortar"}
		{link_sound "rotate_gun" "vehicle/turret/medium"}
		{add_view	"flash_cannon_small"		"flashbarrel1"	"Foresight1"}
		{add_view	"powdersmoke_big"		"flashbarrel1s"		"Foresight1"}
		{add_view	"smoke_zenite"		    "smkafire"		"Foresight1"}
	}
	{on fire "gun"
        		{view start "flashbarrel1"}
		{view start "flashbarrel1s"}
        		{view start "smkafire"}
		{delay 0.8
			{view pause "flashbarrel1"}
		}
		{delay 0.2
			{view pause "flashbarrel1s"}
		}
        		{delay 2.5
            			{view stop "smkafire"}
        		}
	}
}
{"stz3  tank" 
	("stz_sound")
 	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass" args 1 _front)
		else volume "glass_back"
 			("break_glass" args 3 _back)
		else volume "glass_left"
 			("break_glass" args 3 _left)
		else volume "glass_right"
 			("break_glass" args 3 _right)
		else volume "glass_headlightl1"
 			("break_glass" args 3 _headlightl1)
		else volume "glass_headlightl"
 			("break_glass" args 3 _headlightl)
		else volume "glass_headlightr1"
 			("break_glass" args 3 _headlightr1)
		else volume "glass_headlightr"
 			("break_glass" args 3 _headlightr)
		}
	}
}
{"stz3_chn  tank" 
	("stz_sound")
 	{on bullet_hit
 		{if volume "glass_front"
 			("break_glass" args 1 _front)
		else volume "glass_back"
 			("break_glass" args 3 _back)
		else volume "glass_left"
 			("break_glass" args 3 _left)
		else volume "glass_right"
 			("break_glass" args 3 _right)
		else volume "glass_headlightl1"
 			("break_glass" args 3 _headlightl1)
		else volume "glass_headlightl"
 			("break_glass" args 3 _headlightl)
		else volume "glass_headlightr1"
 			("break_glass" args 3 _headlightr1)
		else volume "glass_headlightr"
 			("break_glass" args 3 _headlightr)
		}
	}
}
{"staghound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/wheels/wheels"			}
		{link_sound "engine"			"vehicle/engine/sdkfz234"		}
		{link_sound "engine_end"		"vehicle/engine/sdkfz234_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light1"			}
		{link_sound "exhaust"			"vehicle/engine/sdkfz234_up"	}
		{link_sound "idle"			"vehicle/engine/sdkfz_idle"		}
	}
	("burn_by_engine" args 0.3)
}
{"staghound_e1"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/wheels/wheels"			}
		{link_sound "engine"			"vehicle/engine/sdkfz234"		}
		{link_sound "engine_end"		"vehicle/engine/sdkfz234_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light1"			}
		{link_sound "exhaust"			"vehicle/engine/sdkfz234_up"	}
		{link_sound "idle"			"vehicle/engine/sdkfz_idle"		}
	}
	("burn_by_engine" args 0.3)
}
{"pz1b_39 tank"
	{on spawn
		{add_view	"flash_gun_big_vehicle"	"flashbarrel00"	"shooter00"	}
		{add_view	"flash_gun_big_vehicle"	"flashbarrel01"	"shooter01"	}
	}
	{on fire "mgun" overload
		{if  name "00"
			{view start "flashbarrel00"}
			{delay 0.5
				{view pause "flashbarrel00"}
			}
		else name "01"
			{view start "flashbarrel01"}
			{delay 0.5
				{view pause "flashbarrel01"}
			}
		}
	}
	("pz1_sound")
	("burn_by_engine" args 0.3)    
}
{"sdkfz223_39 tank" 
	("sdkfz_sound")
	("burn_by_engine" args 0.3) 
}
{"np_sdkfz231_39 tank"
	("sdkfz234_sound")
	("burn_by_engine" args 0.3) 
}
{"sdkfz232_39 tank"
	("sdkfz234_sound")
	("burn_by_engine" args 0.3) 
}
{"sdkfz222_39 tank" 
	("sdkfz_sound")
	("burn_by_engine" args 0.3)
}
{"pz2c_39 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/pz2"		}
		{link_sound "engine"			"vehicle/engine/pz2"		}
		{link_sound "engine_end"		"vehicle/engine/pz2_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/light1"		}
		{link_sound "exhaust"			"vehicle/engine/pz2_up" 	}
		{link_sound "idle"			"vehicle/engine/pz2_idle"		}
	}
	("burn_by_engine" args 0.3) 
}
{"pzkpfw35t_39 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/pz35t"		}
		{link_sound "engine"			"vehicle/engine/pz35"		}
		{link_sound "engine_end"		"vehicle/engine/pz35_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/pz38t_turret"	}
		{link_sound "exhaust"			"vehicle/engine/pz35_up"	}
		{link_sound "idle"			"vehicle/engine/pz35"		}
	}
	("burn_by_engine" args 0.3) 
}
{"pzkpfw38t_39 tank" 
	("pz38_sound")
	("burn_by_engine" args 0.3)
}
{"pz3e_39 tank"
	{on spawn
		{add_view	"flash_gun_big"	"flashbarrel00"	"shooter00"	}
		{add_view	"flash_gun_big"	"flashbarrel01"	"shooter01"	}
	}
	{on fire "mgun2" overload
		{if  name "00"
			{view start "flashbarrel00"}
			{delay 0.8
				{view pause "flashbarrel00"}
			}
		else name "01"
			{view start "flashbarrel01"}
			{delay 0.8
				{view pause "flashbarrel01"}
			}
		}
	}
	("pz3_sound")
	("burn_by_engine" args 0.3) 
}
{"t80 tank"
	("t70_sound")
	("burn_by_engine" args 0.3)
}
{"jagdpanther tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/jugdpanther"  		}
		{link_sound "engine"			"vehicle/engine/jugdpanther"		}
		{link_sound "engine_end"		"vehicle/engine/jugdpanther_end"	}
		{link_sound "exhaust"			"vehicle/engine/jugdpanther_up" 	}
		{link_sound "rotate_turret" 	"vehicle/turret/heavy1"	}
		{link_sound "idle"			"vehicle/engine/pz5_idle"		}
	}
	("burn_by_engine" args 0.3)

	{on "stop_on"
		{ani_play "antenna"}
	}
	{on move on
		{ani_play "antenna" -1}
	}
	{on fire "gun"
		{ani_play "antenna"}
	}
}
{"t34_3c tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/t34"	}
		{link_sound "rotate_turret" 	"vehicle/turret/t34"		}
		{link_sound "engine"			"vehicle/engine/t3485"		}
		{link_sound "engine_end"		"vehicle/engine/t3485_end"	}
		{link_sound "exhaust"			"vehicle/engine/m3a1_up"	}
		{link_sound "idle"			"vehicle/engine/t34_idle"		}
	}
	("burn_by_engine" args 0.3)
}
{"m30kangaroo tank"
	{on "add_movement_sound" overload
		{link_sound "move"					"vehicle/tracks/m7"		}
		{link_sound "engine"				"vehicle/engine/m7"		}
		{link_sound "engine_end"			"vehicle/engine/m7_end"	}
		{link_sound "exhaust"				"vehicle/engine/m4a2_up"	}
		{link_sound "idle"			"vehicle/engine/m4a2_idle"		}
	}
	("burn_by_engine" args 0.3)
}
{"pz1a_flamm tank"
	{on spawn
		{add_view "flamer_fire" "flame1" "foresight1"}
		{add_view "flamer_fire_barrel" "fire1" "foresight1"}
		{view show	"fire1"}
		{view start	"fire1"}
	}
	{on operatable on	
		{view start	"fire1"}
	}	
	{on operatable off		
		{view stop	"fire1"}
	}
	{on break_armor
		{if name "blast"
			{if volume "body"
				{call "explosion"}
			}
                		}
	}
	{on bullet_hit
		{if volume "body"
			{if  tagged "isbodypierced"
				{if rand 0.3
					{call "_explosion"}
					{tags remove "isbodypierced"}
				}
			}
		}
	}
	{on "_explosion"
		{call "__explosion"}
		{spawn "fuel_die"}
		{blastwave c4 5 r0 4 r1 15}
		{fire radius 5 time 15 heating 10}
	}
	{on "__explosion"
		{set "big_explosion" 0}
		{if explosive_amount 50         
			{blastwave c4 30 r0 8 r1 16}     
			{blastwave c4 3 r0 20 r1 30}
			{spawn "train_die" "basis"}
			{set "big_explosion" 1}
		}
	}
	{on fire "flamer1"
		{view start	"flame1"}
		{kill_delay "fire1"}
		{delay 0.5 "fire1"
			{view pause	"flame1"}
		}
	}
	("pz1_sound")
	("burn_by_engine" args 0.3)    
}
{"mk-iv-mgun tank"
	{on fire "mgun1"
               	{spawn "flash_gun_big" "Foresight4" x}
	}
	{on fire "mgun2"
               {spawn "flash_gun_big" "Foresight5" x}
	}
	{on fire "mgun3"
               {spawn "flash_gun_big" "Foresight6" x}
	}
	{on fire "mgun4"
               {spawn "flash_gun_big" "Foresight7" x}
	}
	("mkiv_sound")
}
{"mk-iv tank"
	{on spawn
		{add_view	 "flash_cannon_big"		"flashbarrel11"		"Foresight11"}
		{add_view	 "powdersmoke_big"		"flashbarrel11s"	"Foresight11"}
	}
	{on fire "gun2"
 		{view start "flashbarrel11"}
		{view start "flashbarrel11s"}
        		{view start "smkafire"}
		{delay 0.8
			{view pause "flashbarrel11"}
		}
		{delay 0.2
			{view pause "flashbarrel11s"}
		}
        		{delay 2.5
            			{view stop "smkafire"}
       		}
	}
	("mkiv_sound")
}
{"cruisermk3 tank"
	{on "add_movement_sound" overload
		{link_sound "move"		    	"vehicle/tracks/cromwell"	}
		{link_sound "engine"			"vehicle/engine/pz2"		}
		{link_sound "engine_end"		"vehicle/engine/pz2_end"	}
		{link_sound "exhaust"			"vehicle/engine/pz2_up" 	}
		{link_sound "rotate_turret" 	"vehicle/turret/medium1"		}
		{link_sound "idle"			"vehicle/engine/pz2_idle"		}
	}
}
{"crusaderi tank"
	("mk6_sound")
	("burn_by_engine" args 0.3)
	{on fire "gun"
		{ani_play "fire"}
		{ani_play "start"}
	}
}
{"crusaderics tank"
	("mk6_sound")
	("burn_by_engine" args 0.3)
	{on fire "gun"
		{ani_play "fire"}
		{ani_play "start"}
	}
}
{"crusaderii tank"
	("mk6_sound")
	("burn_by_engine" args 0.3)
	{on fire "gun"
		{ani_play "fire"}
		{ani_play "start"}
	}
}
{"pz3l tank"
	("pz3_sound")
	("burn_by_engine" args 0.3)
	{on fire "gun"
        		{ani_play "fire2"}
	}	
}
{"m46_patton tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m26"	}
		{link_sound "rotate_turret" 	"vehicle/turret/pershing"		}
		{link_sound "engine"			"vehicle/engine/m26"		}
		{link_sound "engine_end"		"vehicle/engine/m4a2_end"	}
		{link_sound "exhaust"			"vehicle/engine/m4a2_up"	}
		{link_sound "idle"			"vehicle/engine/m26_idle"		}
	}
	("burn_by_engine" args 0.3)
}
{"stug3f_8 tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}
{"stug4g tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}
{"hetzer" 
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/hetzer"	}
		{link_sound "engine"			"vehicle/engine/hetzer"		}
		{link_sound "engine_end"		"vehicle/engine/hetzer_end"	}
		{link_sound "exhaust"			"vehicle/engine/hetzer_up"	}
		{link_sound "idle"			"vehicle/engine/hetzer_idle"		}
	}
	("burn_by_engine" args 0.3)
	("shell_ejection_tank")
}
{"churchill_mk_viii tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/churchill"		}
		{link_sound "engine"			"vehicle/engine/churchill"		}
		{link_sound "engine_end"		"vehicle/engine/churchill_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/churchill_turret"	}
		{link_sound "exhaust"			"vehicle/engine/churchill_up" 	}
		{link_sound "idle"			"vehicle/engine/churchill"		}
	}
	("burn_by_engine" args 0.3)
}
{"wolverine tank"
	("m10wolverine_sound")
	{on "gunner_hatch_open" overload
		{ani_play "close"}
	}
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"chi-he_m tank"
	{on "add_movement_sound" overload
		{link_sound "rotate_turret" 	"vehicle/turret/medium"	}
		{link_sound "move"				"vehicle/tracks/m26"	}
		{link_sound "engine"			"vehicle/engine/chi-ha"	}
		{link_sound "engine_end"		"vehicle/engine/tank_end"}
		{link_sound "exhaust"			"vehicle/engine/tank_up"	}
		{link_sound "idle"			"vehicle/engine/chi-ha"	}
	}
	("burn_by_engine" args 0.3)
}
{"chi-ha_eng tank"
	{on "add_movement_sound" overload
		{link_sound "rotate_turret" 	"vehicle/turret/light"	}
		{link_sound "move"				"vehicle/tracks/chi-ha"	}
		{link_sound "engine"			"vehicle/engine/chi-ha"	}
		{link_sound "engine_end"		"vehicle/engine/hetzer_end"}
		{link_sound "exhaust"			"vehicle/engine/hetzer_up"	}
		{link_sound "idle"			"vehicle/engine/chi-ha"	}
	}
	("burn_by_engine" args 0.3)
}
{"s35_ger tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/mk2"		}
		{link_sound "engine"			"vehicle/engine/somua"		}
		{link_sound "engine_end"		"vehicle/engine/somua_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/small1"	}
		{link_sound "exhaust"			"vehicle/engine/somua_up" 	}
		{link_sound "idle"			"vehicle/engine/somua"		}
	}
	("burn_by_engine" args 0.3)
}
{"is2_43 tank"
	("is_sound")
	{on "gunner_hatch_open" overload
		{ani_play "open2"}
	}
	("burn_by_engine" args 0.2)
}
{"sdkfz222 tank" 
	("sdkfz_sound")
	{on spawn
		{set "rotate_turret_3ro" 0}
		{set "chassis_work_turret" 1}
		{set "chassis_work" 1}
	}
	{on ik begin "turret"
		{kill_delay "rotate_turret"}
		{if not "rotate_turret_3ro"
			{set "rotate_turret_3ro" 1}
			{If "chassis_work"
				{set "chassis_work" 0}
				{ani_play "open2"}
				{play_sound "rotate_turret" 1}
				{set  "chassis_work_turret" 1}
			else
				{set  "chassis_work_turret" 0}
				
			}	
		}
	}
	{on ik end "turret"
		{if "rotate_turret_3ro"
			{set "chassis_work" 1}
		}
		{delay 0.5 "rotate_turret"
			{stop_sound "rotate_turret"}
			
		}
	}
	{on move on
		{if "rotate_turret_3ro"
			{set "rotate_turret_3ro" 0}
			{if work "turret"
				;{ik_enable "turret" 0}
				{ani_play "open2" -1}
				
			}
		}
		{set "engine_on" 1}
		{stop_sound "idle"}
		{stop_sound "move_end"}
		{play_sound "move" 1}
		{play_sound "exhaust"}
		{call "exhaust_on"}
		{ani_stop "stop"}
		{ani_play "start"}
		{view pause "exhaust2"}
	}
	{on move off
		{If not "rotate_turret_3ro"
			{if work "turret"
				;{ik_enable "turret" 1}
				{set "chassis_work_turret" 1}
			}
		}
		{stop_sound "move"}
		{play_sound "move_end"}
		{call "exhaust_off"}
	}
	("burn_by_engine" args 0.3)
}
{"sdkfz231_8rad tank"
	("sdkfz234_sound")
	("burn_by_engine" args 0.3) 
}
{"sdkfz231_8rad_39 tank"
	("sdkfz234_sound")
	("burn_by_engine" args 0.3) 
}
{"m4a2 tank"
	("m4a2_sound")
	("burn_by_engine" args 0.3)
}
{"m4a2_pol tank"
	("m4a2_sound")
	("burn_by_engine" args 0.3)
}
{"mk4_rus tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/churchill"		}
		{link_sound "engine"			"vehicle/engine/churchill"		}
		{link_sound "engine_end"		"vehicle/engine/churchill_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/churchill_turret"	}
		{link_sound "exhaust"			"vehicle/engine/churchill_up" 	}
		{link_sound "idle"			"vehicle/engine/churchill"		}
	}
	("burn_by_engine" args 0.3)
}
{"mk3_rus tank"
	("bishop_sound")
	("burn_by_engine" args 0.3)
}
{"m10wolverine_44"
	("m10wolverine_sound")
	{on "gunner_hatch_open" overload
		{ani_play "close"}
	}
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"t-20 tank"
	("su76_sound")
	("burn_by_engine" args 0.3)
}
{"sig33b tank"
	("pz4_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"grille tank" 
	("pz38_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"m4a3m_eng tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m4a2"  }
		{link_sound "engine"			"vehicle/engine/m4a2"		}
		{link_sound "engine_end"		"vehicle/engine/m4a2_end"	}
		{link_sound "exhaust"			"vehicle/engine/m4a2_up"	}
		{link_sound "rotate_turret" 	"vehicle/turret/heavy"	}
		{link_sound "idle"			"vehicle/engine/m4a2_idle"		}
	}
	("burn_by_engine" args 0.3)
}
{"landsverk180 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/wheels/wheels"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light1"	}
		{link_sound "engine"			"vehicle/engine/Blitz"   	}
		{link_sound "engine_end"		"vehicle/engine/Blitz_end"	}
		{link_sound "exhaust"			"vehicle/engine/Blitz_up"	}
		{link_sound "idle"			"vehicle/engine/truck_idle"   	}
	}
	("burn_by_engine" args 0.2)
}
{"sdkfz247 tank"
	("sdkfz_sound")
	("burn_by_engine" args 0.3)
}
{"morriscs9 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/wheels/wheels"		}
		{link_sound "move_end"			"vehicle/wheels/car_end"	}
		{link_sound "engine"			"vehicle/engine/dodge_move" 		}
		{link_sound "engine_end"		"vehicle/engine/dodge_end" 	}
		{link_sound "exhaust"			"vehicle/engine/dodge_up"	}
		{link_sound "idle"			"vehicle/engine/dodge" 		}
	}
}
{"t29 tank"
	{on spawn
		{add_view	"flash_gun_big"	"flashbarrel00"	"shooter00"	}
		{add_view	"flash_gun_big"	"flashbarrel01"	"shooter01"	}
	}
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m26"	}
		{link_sound "rotate_turret" 	"vehicle/turret/pershing"		}
		{link_sound "engine"			"vehicle/engine/m26"		}
		{link_sound "engine_end"		"vehicle/engine/m4a2_end"	}
		{link_sound "exhaust"			"vehicle/engine/m4a2_up"	}
		{link_sound "idle"			"vehicle/engine/m26_idle"		}
	}
	("burn_by_engine" args 0.3)
	{on "gunner_hatch_open" overload
		{ani_play "open2"}
	}
	{on fire "mgun2" overload
		{if  name "00"
			{view start "flashbarrel00"}
			{delay 0.8
				{view pause "flashbarrel00"}
			}
		else name "01"
			{view start "flashbarrel01"}
			{delay 0.8
				{view pause "flashbarrel01"}
			}
		}
	}
}
{"stug3a tank"
	("pz3_sound")
	("burn_by_engine" args 0.3)
}
{"t34_2f tank"
	("t34_sound")
	("burn_by_engine" args 0.2)
}
{"lvt4_a tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/us_lt_run"	}
		{link_sound "engine"				"vehicle/engine/us_lvt_idle"	}
		{link_sound "engine_end"			"vehicle/engine/us_lvt_revdown"	}
		{link_sound "exhaust"				"vehicle/engine/us_lvt_revup"	}
		{link_sound "rotate_turret" 	    "vehicle/turret/medium2"	}
		{link_sound "idle"			"vehicle/engine/us_lvt_idle"	}
	}
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"lvt4_wb2 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/us_lt_run"	}
		{link_sound "engine"				"vehicle/engine/us_lvt_idle"	}
		{link_sound "engine_end"			"vehicle/engine/us_lvt_revdown"	}
		{link_sound "exhaust"				"vehicle/engine/us_lvt_revup"	}
		{link_sound "idle"			"vehicle/engine/us_lvt_idle"	}
	}
	("burn_by_engine" args 0.3)
}
{"sdkfz221_pzb tank"
	("sdkfz_sound")
	("burn_by_engine" args 0.3)
}
{"m17_pol tank"
	("m3_sound")
	("burn_by_engine" args 0.3)
}
{"m3_stuart tank"
	("m2a4_sound")
	{on "init_gun"
		{add_view	"flash_gun_big_vehicle"	"flashbarrel7"	"Foresight7"}
	}
	{on fire "mgun4"
		{view start "flashbarrel7"}
		{delay 0.5
			{view pause "flashbarrel7"}
		}
	}
	{on fire "gun"
				{ani_play "fire"}
        		{ani_play "start"}
	}
	("burn_by_engine" args 0.3)
}
{"m3_stuart_en tank"
	("m2a4_sound")
	{on "init_gun"
		{add_view	"flash_gun_big_vehicle"	"flashbarrel7"	"Foresight7"}
	}
	{on fire "mgun4"
		{view start "flashbarrel7"}
		{delay 0.5
			{view pause "flashbarrel7"}
		}
	}
	{on fire "gun"
				{ani_play "fire"}
        		{ani_play "start"}
	}
	("burn_by_engine" args 0.3)
}
{"m3_satan tank"
	("m2a4_sound")
	{on spawn
		{add_view "flamer_fire" "flame1" "foresight1"}
		{add_view "flamer_fire_barrel" "fire1" "foresight1"}
		{add_view "flamer_fire" "flame2" "foresight7"}
		{add_view "flamer_fire_barrel" "fire2" "foresight7"}
		{add_view "flamer_fire" "flame3" "foresight8"}
		{add_view "flamer_fire_barrel" "fire3" "foresight8"}
		{add_view "flamer_fire" "flame4" "foresight9"}
		{add_view "flamer_fire_barrel" "fire4" "foresight9"}
		{add_view "flamer_fire" "flame5" "foresight10"}
		{add_view "flamer_fire_barrel" "fire5" "foresight10"}
		{view show	"fire1"}
		{view start	"fire1"}
	}
	{on operatable on	
		{view start	"fire1"}
	}	
	{on operatable off		
		{view stop	"fire1"}
	}
	{on break_armor
		{if name "blast"
			{if volume "body"
				{call "explosion"}
			}
                		}
	}
	{on bullet_hit
		{if volume "body"
			{if  tagged "isbodypierced"
				{if rand 0.3
					{call "_explosion"}
					{tags remove "isbodypierced"}
				}
			}
		}
	}
	{on "_explosion"
		{call "__explosion"}
		{spawn "fuel_die"}
		{blastwave c4 5 r0 4 r1 15}
		{fire radius 5 time 15 heating 10}
	}
	{on "__explosion"
		{set "big_explosion" 0}
		{if explosive_amount 50         
			{blastwave c4 30 r0 8 r1 16}     
			{blastwave c4 3 r0 20 r1 30}
			{spawn "train_die" "basis"}
			{set "big_explosion" 1}
		}
	}
	{on fire "flamer1"
		{view start	"flame1"}
		{kill_delay "fire1"}
		{delay 0.5
			{view pause	"flame1"}
		}
		{view start	"flame2"}
		{delay 0.5
			{view pause	"flame2"}
		}
		{view start	"flame3"}
		{delay 0.5
			{view pause	"flame3"}
		}
		{view start	"flame4"}
		{delay 0.5
			{view pause	"flame4"}
		}
		{view start	"flame5"}
		{delay 0.5 "fire1"
			{view pause	"flame5"}
		}
	}
	("burn_by_engine" args 0.3)
}
{"wasp tank"
	{on spawn
		{add_view "flamer_fire" "flame1" "foresight1"}
		{add_view "flamer_fire_barrel" "fire1" "foresight1"}
		{view show	"fire1"}
		{view start	"fire1"}
	}
	("mk7_sound")
	{on operatable on	
		{view start	"fire1"}
	}	
	{on operatable off		
		{view stop	"fire1"}
	}
	{on break_armor
		{if name "blast"
			{if volume "body"
				{call "explosion"}
			}
                		}
	}
	{on bullet_hit
		{if volume "body"
			{if  tagged "isbodypierced"
				{if rand 0.3
					{call "_explosion"}
					{tags remove "isbodypierced"}
				}
			}
		}
	}
	{on "_explosion"
		{call "__explosion"}
		{spawn "fuel_die"}
		{blastwave c4 5 r0 4 r1 15}
		{fire radius 5 time 15 heating 10}
	}
	{on "__explosion"
		{set "big_explosion" 0}
		{if explosive_amount 50         
			{blastwave c4 30 r0 8 r1 16}     
			{blastwave c4 3 r0 20 r1 30}
			{spawn "train_die" "basis"}
			{set "big_explosion" 1}
		}
	}
	{on fire "flamer1"
		{view start	"flame1"}
		{kill_delay "fire1"}
		{delay 0.5 "fire1"
			{view pause	"flame1"}
		}
	}
	("burn_by_engine" args 0.3)
}
{"staghound_mk3"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/wheels/wheels"			}
		{link_sound "engine"			"vehicle/engine/sdkfz234"		}
		{link_sound "engine_end"		"vehicle/engine/sdkfz234_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/light1"			}
		{link_sound "exhaust"			"vehicle/engine/sdkfz234_up"	}
		{link_sound "idle"			"vehicle/engine/sdkfz_idle"		}
	}
	("burn_by_engine" args 0.3)
}
{"morriscs9_eng tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/wheels/wheels"		}
		{link_sound "move_end"			"vehicle/wheels/car_end"	}
		{link_sound "engine"			"vehicle/engine/dodge_move" 		}
		{link_sound "engine_end"		"vehicle/engine/dodge_end" 	}
		{link_sound "exhaust"			"vehicle/engine/dodge_up"	}
		{link_sound "idle"			"vehicle/engine/dodge" 		}
	}
}
{"dingo tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/wheels/wheels"			}
		{link_sound "engine"			"vehicle/engine/sdkfz234"		}
		{link_sound "engine_end"		"vehicle/engine/sdkfz234_end"	}
		{link_sound "exhaust"			"vehicle/engine/sdkfz234_up"	}
		{link_sound "idle"			"vehicle/engine/sdkfz234"		}
	}
	("burn_by_engine" args 0.3)
}
{"sexton"
	("m7_sound")
	("shell_ejection_tank")
	("burn_by_engine" args 0.3)
}
{"jpz4l48 tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}
{"m4a3e2_jumbo_76w tank"
	{on "add_movement_sound" overload
		{link_sound "move"					"vehicle/tracks/m4a2"		}
		{link_sound "engine"				"vehicle/engine/m4"		}
		{link_sound "engine_end"			"vehicle/engine/m4_end"	}
		{link_sound "exhaust"				"vehicle/engine/m4a2_up"	}
		{link_sound "rotate_turret" 	    "vehicle/turret/sherman"	}
		{link_sound "idle"			"vehicle/engine/m4a2_idle"		}
	}
	("burn_by_engine" args 0.3)
}
{"cromwell_mk_viii tank"
	{on "add_movement_sound" overload
		{link_sound "move"		    	"vehicle/tracks/cromwell"	}
		{link_sound "engine"			"vehicle/engine/cromwell"		}
		{link_sound "engine_end"		"vehicle/engine/cromwell_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/churchill_turret"	}
		{link_sound "exhaust"			"vehicle/engine/cromwell_up"	}
		{link_sound "idle"			"vehicle/engine/cromwell_idle"		}
	}
	("burn_by_engine" args 0.3)
}
{"cromwell_mk_iv tank"
	{on "add_movement_sound" overload
		{link_sound "move"		    	"vehicle/tracks/cromwell"	}
		{link_sound "engine"			"vehicle/engine/cromwell"		}
		{link_sound "engine_end"		"vehicle/engine/cromwell_end"	}
		{link_sound "rotate_turret" 	"vehicle/turret/churchill_turret"	}
		{link_sound "exhaust"			"vehicle/engine/cromwell_up"	}
		{link_sound "idle"			"vehicle/engine/cromwell_idle"		}
	}
	("burn_by_engine" args 0.3)
}
{"m4a1s tank"
	("m4a2_sound")
	("burn_by_engine" args 0.3)
}
{"grant_m3 tank"
	{on spawn
		{add_view	"flash_gun_big"	"flashbarrel00"	"shooter00"	}
		{add_view	"flash_gun_big"	"flashbarrel01"	"shooter01"	}
	}
	("m4_sound")
	("burn_by_engine" args 0.3)
	{on fire "gun2"
        		{view start "flashbarrel11"}
		{view start "flashbarrel11s"}
		{ani_play "fire2"}
		{delay 0.8
			{view pause "flashbarrel11"}
		}
		{delay 0.2
			{view pause "flashbarrel11s"}
		}
	}
	{on fire "mgun" overload
		{if  name "00"
			{view start "flashbarrel00"}
			{delay 0.5
				{view pause "flashbarrel00"}
			}
		else name "01"
			{view start "flashbarrel01"}
			{delay 0.5
				{view pause "flashbarrel01"}
			}
		}
	}
}
;-----------------Normand Unit Pack