{"pzkpfw38t_bul tank"
	("pz38_sound")
	("burn_by_engine" args 0.3)
}

{"pzkpfw35t_bul tank"
	("pz38_sound")
	("burn_by_engine" args 0.3)
}
{"r35_bul tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/r35"		}
		{link_sound "engine"			"vehicle/engine/r35"		}
		{link_sound "engine_end"		"vehicle/engine/r35_end"	}
		{link_sound "exhaust"			"vehicle/engine/r35_up"	}
		{link_sound "rotate_turret" 	"vehicle/turret/pz38t_turret"	}
		{link_sound "idle"			"vehicle/engine/r35"		}
	}
	("burn_by_engine" args 0.2)
}
{"pz4g_bul tank"
	("pz4_sound")
	("burn_by_engine" args 0.3)
}
{"stug3g_bul tank"
	("stug_sound")
	("burn_by_engine" args 0.3)
}
{"sdkfz222_bul tank"
	("sdkfz_sound")
	("burn_by_engine" args 0.3)
}
{"sdkfz223_bul tank"
	("sdkfz_sound")
	("burn_by_engine" args 0.3)
}
{"h39_bul tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/r35"		}
		{link_sound "engine"			"vehicle/engine/m3a1_stuart"	}
		{link_sound "engine_end"		"vehicle/engine/m3a1_stuart_end"}
		{link_sound "rotate_turret" 		"vehicle/turret/small1"	}
		{link_sound "exhaust"			"vehicle/engine/m3a1_stuart_up"	}
		{link_sound "idle"			"vehicle/engine/m3a1_stuart"	}
	}
	("burn_by_engine" args 0.3)
}
{"s35_bul tank"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/mk2"		}
		{link_sound "engine"			"vehicle/engine/somua"		}
		{link_sound "engine_end"		"vehicle/engine/somua_end"	}
		{link_sound "rotate_turret" 		"vehicle/turret/small1"	}
		{link_sound "exhaust"			"vehicle/engine/somua_up" 	}
		{link_sound "idle"			"vehicle/engine/somua"		}
	}
	("burn_by_engine" args 0.3)
}
{"vickers_bul tank"
	("t26_sound")
	("burn_by_engine" args 0.2) 
} 
{"t11_bul tank"
	("pz38_sound")
	("burn_by_engine" args 0.3)
}
{"sdkfz232_bul tank"
	("sdkfz234_sound")
	("burn_by_engine" args 0.3)
}
{"l335_bul tank"
	("l335_sound")
	("burn_by_engine" args 0.3)
}
{"m4732_bul tank"
	("l640_sound")
	("burn_by_engine" args 0.3)
}