{weapon_bullet
	{tag "mrl gun"}
	{filling "ammo mortar120" 1}
	{fillingVisible "rocket"}

	{fireSound "reactive/mortar"}
	{foresight "foresight"}
	
	{recoveryTime 6}
	{rechargeTime 6}
	{RelaxationTime 1.2}
	{AimingTolerance 0.1}
	{cursor "cannon_on_fg"}
	{cursorReloading "cannon_reload_fg"}
	
	{parameters "sm"
		{cursor "cannon_on_sm"}
		{cursorReloading "cannon_reload_sm"}
	}
	
	{parameters "ic"
		{cursor "cannon_on_ic"}
		{cursorReloading "cannon_reload_ic"}
	}
	
	{parameters "wp"
		{cursor "cannon_on_wp"}
		{cursorReloading "cannon_reload_wp"}
        	}
	
	{parameters "fl"
		{cursor "cannon_on_fl"}
		{cursorReloading "cannon_reload_fl"}
	}
	("heavy_mortar")
}
